server :
  port : 8080
spring :
  datasource :
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/we_db?allowMultiQueries=true
    username : ${DB_USERNAME:root}
    password : ${DB_PASSWORD:password}


mybatis :
  type-aliases-package: com.wewtapi
  mapper-locations: classpath:mapper/*.xml
